# Generated by Django 3.0.6 on 2020-07-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_prodeuct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodeuct',
            new_name='Product',
        ),
    ]
